name: 'ASD'
on:
 push:
   branches:
     - main
permissions: 
 id-token: write
 contents: read
 

jobs:
  terraform:
    runs-on: self-hosted

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Azure Login
      uses: azure/login@v2
      with:
         tenant-id: ${{vars.tenamt_id}}
         clint-id: ${{vars.clint_id}}
         subcription-id: ${{vars.subcription_id}}


    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Terraform Init
      run: terraform init

    - name: Terraform Format
      run: terraform fmt -check

    - name: Terraform Validate
      run: terraform validate

    - name: Terraform Plan
      run: terraform plan -out=tfplan
     - name: Terraform Plan
       run: terraform plan
         
         
